### ISSUE TITLE
Not a bug report!

### ISSUE THREAD

**Issue by cmtonkinson** [lexicalunit/multi-wrap-guide#11]
Just a friendly holler; thanks for the excellent package! It's a perfect complement to our own (https://github.com/forgecrafted/rulerz) - in fact, we'd have started working on stationary guides ourselves had you not stepped up to it! Keep it up!

**Comment by lexicalunit** [comment]
Thanks! I was just looking at your package coincidentally. My code could stand to be refactored more cleanly, heh.

**Comment by cmtonkinson** [comment]
> code could stand to be refactored

Said every developer ever. ;-)
