### ISSUE TITLE
Windows 7: Icons in "Multi Wrap Guide" context menu don't show well.

### ISSUE THREAD

**Issue by phoenixenero** [lexicalunit/multi-wrap-guide#19]
![1533c34f61](https://cloud.githubusercontent.com/assets/9031092/15090441/7214767a-145a-11e6-86d4-de04451d3807.png)

**Comment by lexicalunit** [comment]
Awww that sucks 😞 

I wonder if there's a way to disable the icons specifically for Windows, or use icons that will show up in Windows...

**Comment by lexicalunit** [comment]
What about the `Multi Wrap Guide` sub menu in the `Packages` main menu? For example on OS X it looks like this:

<img width="490" alt="screen shot 2016-05-07 at 12 57 04 am" src="https://cloud.githubusercontent.com/assets/1903876/15090478/b60027ce-13ee-11e6-862c-26169ee0797f.png">

**Comment by phoenixenero** [comment]
Yep, doesn't quite look the best...
![ss 2016-05-08 at 10 06 28](https://cloud.githubusercontent.com/assets/9031092/15095643/bab10772-1504-11e6-97f2-68b508e2e21e.png)

**Comment by lexicalunit** [comment]
@phoenixenero Sorry it took me so long to circle around back to this. There's now an option to disable icons which should resolve issues on systems that can not properly display them.
