### ISSUE TITLE
Create PR at atom/wrap-guide

### ISSUE THREAD

**Issue by pedzed** [lexicalunit/multi-wrap-guide#23]
Could you create a PR for https://github.com/atom/wrap-guide so that it will be in every default Atom installation?

**Comment by lexicalunit** [comment]
That would be pretty cool! Though both packages provide a similar feature, `multi-wrap-guide` truly is a completely different package than `wrap-guide`. I'm not sure how the Atom devs would feel about a PR that would touch just about 100% of the code in the `wrap-guide` repository. However I have seen cases where community packages take over core package before though; for example: autocomplete-plus. CC: @kevinsawicki, @lee-dohm your thoughts?

**Comment by pedzed** [comment]
> multi-wrap-guide truly is a completely different package than wrap-guide

You are right, it is a completely different package and I should have mentioned that. But to be honest, I only cared for the support of multiple guides :smirk: 

As you are aware, there is an issue open at atom/wrap-guide/issues/14. In regards to touching about 100% of their codebase, what about creating smaller PR's? Or is it too much work to split it up? I would understand if it's unreasonable to do that.

**Comment by lexicalunit** [comment]
I could probably factor out parts of the code that would provide a bare-bones, vertical-only, non-interactive, multi-wrap-guide feature configurable only by editing Atom's `config.cson` file directly &mdash; something similar to [this suggestion](https://github.com/atom/wrap-guide/issues/48#issue-109580216) from @stylemistake. Given that [atom/wrap-guide #14](https://github.com/atom/wrap-guide/issues/14) remains open I'm sure such a PR could be accepted (providing, of course,  proper spec tests and general consensus from Atom devs).

I'm not sure when I'd be able to get around to doing that though :(

**Comment by lee-dohm** [comment]
I'd be open to accepting a PR like the bare-bones one you describe, definitely.

**Comment by lexicalunit** [comment]
@pedzed: I started working on [a bare-bones PR for `wrap-guide`](https://github.com/atom/wrap-guide/pull/56) if you'd like to follow development there. I'll close this ticket now. Thanks for showing your interest in this feature!
