### ISSUE TITLE
ID on the gif's overlay

### ISSUE THREAD

**Issue by 0450** [lexicalunit/multi-wrap-guide#35]
The dotted pattern on the 2 gifs looks so good and I can't stop thinking bout it. Can someone let me in on how do i do that?

**Comment by lexicalunit** [comment]
I made those a few years ago now... I think I used `gifsicle` to do it but I can't remember the settings. Maybe I used some kind of dithering options to try and get the file size down? Sorry I don't have it in my notes what command I used at the time and I've since totally forgot it.
