### ISSUE TITLE
Horizontal rules

### ISSUE THREAD

**Issue by piranna** [lexicalunit/multi-wrap-guide#4]
Allow to set horizontal rules to define end-of-page limits.

**Comment by lexicalunit** [comment]
Been doing some experimentation with this concept in this branch: https://github.com/lexicalunit/multi-wrap-guide/tree/horizontal_rulers Trying to figure out how best to implement it...

**Comment by piranna** [comment]
:+1:

**Comment by lexicalunit** [comment]
Let me know how version 0.17.0 works for you :)
